import { test, expect } from "@playwright/test";

test.describe("Day 1 UI Audit, Redesign & Legal Compliance Pass", () => {
  test("Test 1 — Favicon exists and loads successfully", async ({ request }) => {
    const res = await request.get("/favicon.svg");
    expect(res.status()).toBe(200);
    const contentType = res.headers()["content-type"];
    expect(contentType).toContain("svg");
    const text = await res.text();
    expect(text).toContain("<svg");
  });

  test("Test 2 — No AI branding labels present in application", async ({ page }) => {
    await page.goto("/");
    await page.waitForLoadState("networkidle");

    const content = await page.content();
    expect(content).not.toMatch(/made with ai/i);
    expect(content).not.toMatch(/built with ai/i);
    expect(content).not.toMatch(/generated by ai/i);
  });

  test("Test 3 — Privacy Policy route (/privacy) loads and displays honest prototype policy", async ({ page }) => {
    await page.goto("/privacy");
    await expect(page.getByRole("heading", { name: /PolarOps Privacy/i })).toBeVisible();
    await expect(page.getByText(/No Tracking or PII/i)).toBeVisible();
    await expect(page.getByText(/Synthetic Telemetry/i).first()).toBeVisible();

    // Verify back button returns to Command Center
    const backBtn = page.getByRole("main").getByRole("button", { name: /Return to Command Center/i });
    await expect(backBtn).toBeVisible();
    await backBtn.click();
    await expect(page.getByText(/STATION STATUS/i).first()).toBeVisible();
  });

  test("Test 4 — Terms and Conditions route (/terms) loads with prototype disclaimer", async ({ page }) => {
    await page.goto("/terms");
    await expect(page.getByRole("heading", { name: /Terms of Use & Prototype Disclaimer/i })).toBeVisible();
    await expect(page.getByText(/No Autonomous Actuation/i)).toBeVisible();

    // Verify back button works
    const backBtn = page.getByRole("main").getByRole("button", { name: /Return to Command Center/i });
    await expect(backBtn).toBeVisible();
    await backBtn.click();
    await expect(page.getByText(/STATION STATUS/i).first()).toBeVisible();
  });

  test("Test 5 — Footer contains mission control metadata and legal links", async ({ page }) => {
    await page.goto("/");
    await page.waitForLoadState("networkidle");

    const footer = page.locator("footer");
    await expect(footer).toBeVisible();
    await expect(footer.getByText(/POLAROPS MISSION CONTROL/i)).toBeVisible();
    await expect(footer.getByRole("button", { name: /Privacy Policy/i })).toBeVisible();
    await expect(footer.getByRole("button", { name: /Terms of Use/i })).toBeVisible();

    // Click Privacy Policy from footer
    await footer.getByRole("button", { name: /Privacy Policy/i }).click();
    await expect(page.getByRole("heading", { name: /PolarOps Privacy/i })).toBeVisible();

    // Click Terms of Use from footer
    await footer.getByRole("button", { name: /Terms of Use/i }).click();
    await expect(page.getByRole("heading", { name: /Terms of Use & Prototype Disclaimer/i })).toBeVisible();
  });

  test("Test 6 — Responsive viewport integrity on desktop, laptop, and narrow widths", async ({ page }) => {
    // 1. Desktop 1440x900
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.goto("/");
    await expect(page.getByRole("heading", { name: /POLAROPS/i, level: 1 })).toBeVisible();
    const bodyScrollWidthDesktop = await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth);
    expect(bodyScrollWidthDesktop).toBe(true);

    // 2. Laptop 1024x768
    await page.setViewportSize({ width: 1024, height: 768 });
    await page.reload();
    await expect(page.getByRole("heading", { name: /POLAROPS/i, level: 1 })).toBeVisible();

    // 3. Narrow 768x1024
    await page.setViewportSize({ width: 768, height: 1024 });
    await page.reload();
    await expect(page.getByRole("heading", { name: /POLAROPS/i, level: 1 })).toBeVisible();
  });
});
