"""canonical_domain_models

Revision ID: 7cbd04eb1003
Revises: 
Create Date: 2026-09-06 18:51:33.025826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbd04eb1003'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spare_parts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('criticality', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_part_number'), 'spare_parts', ['part_number'], unique=True)
    op.create_table('stations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('environment_mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_code'), 'stations', ['code'], unique=True)
    op.create_table('buildings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('building_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_station_id'), 'buildings', ['station_id'], unique=False)
    op.create_table('communication_links',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('bandwidth_kbps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_links_station_id'), 'communication_links', ['station_id'], unique=False)
    op.create_table('energy_resources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('current_quantity', sa.Float(), nullable=False),
    sa.Column('max_capacity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('burn_rate_per_hour', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('truth_type', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_resources_station_id'), 'energy_resources', ['station_id'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_category'), 'event_logs', ['category'], unique=False)
    op.create_index(op.f('ix_event_logs_station_id'), 'event_logs', ['station_id'], unique=False)
    op.create_index(op.f('ix_event_logs_timestamp'), 'event_logs', ['timestamp'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_station_id'), 'incidents', ['station_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('spare_part_id', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_spare_part_id'), 'inventory_items', ['spare_part_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_station_id'), 'inventory_items', ['station_id'], unique=False)
    op.create_table('operational_memory',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=False),
    sa.Column('lessons_learned', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_memory_event_type'), 'operational_memory', ['event_type'], unique=False)
    op.create_index(op.f('ix_operational_memory_station_id'), 'operational_memory', ['station_id'], unique=False)
    op.create_table('resupply_opportunities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('spare_part_id', sa.String(length=64), nullable=True),
    sa.Column('vessel_name', sa.String(length=128), nullable=False),
    sa.Column('expected_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resupply_opportunities_spare_part_id'), 'resupply_opportunities', ['spare_part_id'], unique=False)
    op.create_index(op.f('ix_resupply_opportunities_station_id'), 'resupply_opportunities', ['station_id'], unique=False)
    op.create_table('scientific_instruments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('instrument_type', sa.String(length=64), nullable=False),
    sa.Column('health', sa.String(length=32), nullable=False),
    sa.Column('power_status', sa.String(length=32), nullable=False),
    sa.Column('calibration_status', sa.String(length=32), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scientific_instruments_code'), 'scientific_instruments', ['code'], unique=False)
    op.create_index(op.f('ix_scientific_instruments_station_id'), 'scientific_instruments', ['station_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('criticality', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_code'), 'services', ['code'], unique=False)
    op.create_index(op.f('ix_services_station_id'), 'services', ['station_id'], unique=False)
    op.create_table('sync_queue_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_queue_items_event_type'), 'sync_queue_items', ['event_type'], unique=False)
    op.create_index(op.f('ix_sync_queue_items_priority'), 'sync_queue_items', ['priority'], unique=False)
    op.create_index(op.f('ix_sync_queue_items_station_id'), 'sync_queue_items', ['station_id'], unique=False)
    op.create_index(op.f('ix_sync_queue_items_status'), 'sync_queue_items', ['status'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=False),
    sa.Column('wind_speed_knots', sa.Float(), nullable=False),
    sa.Column('wind_chill_celsius', sa.Float(), nullable=False),
    sa.Column('conditions', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('truth_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_station_id'), 'weather_observations', ['station_id'], unique=False)
    op.create_index(op.f('ix_weather_observations_timestamp'), 'weather_observations', ['timestamp'], unique=False)
    op.create_table('operational_actions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('action_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('executed_by', sa.String(length=64), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_actions_incident_id'), 'operational_actions', ['incident_id'], unique=False)
    op.create_table('scientific_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('measurement_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('truth_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['scientific_instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scientific_observations_instrument_id'), 'scientific_observations', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_scientific_observations_timestamp'), 'scientific_observations', ['timestamp'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('building_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('occupancy', sa.Integer(), nullable=False),
    sa.Column('target_temp_celsius', sa.Float(), nullable=False),
    sa.Column('criticality', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_building_id'), 'zones', ['building_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('building_id', sa.String(length=64), nullable=True),
    sa.Column('zone_id', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('criticality', sa.String(length=32), nullable=False),
    sa.Column('commissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_category'), 'assets', ['category'], unique=False)
    op.create_index(op.f('ix_assets_code'), 'assets', ['code'], unique=False)
    op.create_index(op.f('ix_assets_station_id'), 'assets', ['station_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_index(op.f('ix_assets_zone_id'), 'assets', ['zone_id'], unique=False)
    op.create_table('asset_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_asset_id', sa.String(length=64), nullable=False),
    sa.Column('target_asset_id', sa.String(length=64), nullable=True),
    sa.Column('target_service_id', sa.String(length=64), nullable=True),
    sa.Column('dependency_type', sa.String(length=32), nullable=False),
    sa.Column('impact_factor', sa.Float(), nullable=False),
    sa.Column('is_redundant', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['target_service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_dependencies_source_asset_id'), 'asset_dependencies', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_dependencies_target_asset_id'), 'asset_dependencies', ['target_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_dependencies_target_service_id'), 'asset_dependencies', ['target_service_id'], unique=False)
    op.create_table('maintenance_work_orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('required_action', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.String(length=64), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_work_orders_asset_id'), 'maintenance_work_orders', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_priority'), 'maintenance_work_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_status'), 'maintenance_work_orders', ['status'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('min_threshold', sa.Float(), nullable=True),
    sa.Column('max_threshold', sa.Float(), nullable=True),
    sa.Column('warning_threshold', sa.Float(), nullable=True),
    sa.Column('critical_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_asset_id'), 'sensors', ['asset_id'], unique=False)
    op.create_index(op.f('ix_sensors_metric_key'), 'sensors', ['metric_key'], unique=False)
    op.create_table('maintenance_spares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.String(length=64), nullable=False),
    sa.Column('spare_part_id', sa.String(length=64), nullable=False),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['maintenance_work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_spares_spare_part_id'), 'maintenance_spares', ['spare_part_id'], unique=False)
    op.create_index(op.f('ix_maintenance_spares_work_order_id'), 'maintenance_spares', ['work_order_id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('truth_type', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_sensor_id'), 'measurements', ['sensor_id'], unique=False)
    op.create_index('ix_measurements_sensor_timestamp', 'measurements', ['sensor_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_measurements_timestamp'), 'measurements', ['timestamp'], unique=False)
    op.create_index(op.f('ix_measurements_truth_type'), 'measurements', ['truth_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_truth_type'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_timestamp'), table_name='measurements')
    op.drop_index('ix_measurements_sensor_timestamp', table_name='measurements')
    op.drop_index(op.f('ix_measurements_sensor_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_maintenance_spares_work_order_id'), table_name='maintenance_spares')
    op.drop_index(op.f('ix_maintenance_spares_spare_part_id'), table_name='maintenance_spares')
    op.drop_table('maintenance_spares')
    op.drop_index(op.f('ix_sensors_metric_key'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_asset_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_maintenance_work_orders_status'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_priority'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_asset_id'), table_name='maintenance_work_orders')
    op.drop_table('maintenance_work_orders')
    op.drop_index(op.f('ix_asset_dependencies_target_service_id'), table_name='asset_dependencies')
    op.drop_index(op.f('ix_asset_dependencies_target_asset_id'), table_name='asset_dependencies')
    op.drop_index(op.f('ix_asset_dependencies_source_asset_id'), table_name='asset_dependencies')
    op.drop_table('asset_dependencies')
    op.drop_index(op.f('ix_assets_zone_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_station_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_code'), table_name='assets')
    op.drop_index(op.f('ix_assets_category'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_zones_building_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_scientific_observations_timestamp'), table_name='scientific_observations')
    op.drop_index(op.f('ix_scientific_observations_instrument_id'), table_name='scientific_observations')
    op.drop_table('scientific_observations')
    op.drop_index(op.f('ix_operational_actions_incident_id'), table_name='operational_actions')
    op.drop_table('operational_actions')
    op.drop_index(op.f('ix_weather_observations_timestamp'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_station_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_sync_queue_items_status'), table_name='sync_queue_items')
    op.drop_index(op.f('ix_sync_queue_items_station_id'), table_name='sync_queue_items')
    op.drop_index(op.f('ix_sync_queue_items_priority'), table_name='sync_queue_items')
    op.drop_index(op.f('ix_sync_queue_items_event_type'), table_name='sync_queue_items')
    op.drop_table('sync_queue_items')
    op.drop_index(op.f('ix_services_station_id'), table_name='services')
    op.drop_index(op.f('ix_services_code'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_scientific_instruments_station_id'), table_name='scientific_instruments')
    op.drop_index(op.f('ix_scientific_instruments_code'), table_name='scientific_instruments')
    op.drop_table('scientific_instruments')
    op.drop_index(op.f('ix_resupply_opportunities_station_id'), table_name='resupply_opportunities')
    op.drop_index(op.f('ix_resupply_opportunities_spare_part_id'), table_name='resupply_opportunities')
    op.drop_table('resupply_opportunities')
    op.drop_index(op.f('ix_operational_memory_station_id'), table_name='operational_memory')
    op.drop_index(op.f('ix_operational_memory_event_type'), table_name='operational_memory')
    op.drop_table('operational_memory')
    op.drop_index(op.f('ix_inventory_items_station_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_spare_part_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_station_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_event_logs_timestamp'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_station_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_category'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_energy_resources_station_id'), table_name='energy_resources')
    op.drop_table('energy_resources')
    op.drop_index(op.f('ix_communication_links_station_id'), table_name='communication_links')
    op.drop_table('communication_links')
    op.drop_index(op.f('ix_buildings_station_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_stations_code'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_spare_parts_part_number'), table_name='spare_parts')
    op.drop_table('spare_parts')
    # ### end Alembic commands ###
