import { Link, useRouterState } from "@tanstack/react-router";
import { useEffect, useState, type ReactNode } from "react";
import { Activity, AlertTriangle, Archive, BarChart3, Bell, Boxes, ChevronDown, ChevronRight, CircleGauge, ClipboardCheck, Download, FileText, Fuel, Grid3X3, Menu, Minus, Moon, Plus, Radio, RotateCcw, Settings, ShieldCheck, Sun, UserRound, Users, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { demoActivities, demoAlerts, demoDependencies, demoG02, demoMetrics, demoReports, demoResources, demoScenarios, demoStationData, demoTimeline, topologyNodes, type Status } from "@/lib/demo-data";

const navGroups = [
  ["COMMAND", [["Overview", "/", CircleGauge], ["Digital Twin", "/digital-twin", Boxes], ["Stations", "/stations", Radio]]],
  ["OPERATIONS", [["Resources", "/resources", Fuel], ["Scenarios", "/scenarios", Activity], ["Resilience", "/resilience", ShieldCheck], ["Alerts", "/alerts", Bell]]],
  ["REPORTING", [["Reports", "/reports", FileText]]], ["SYSTEM", [["Settings", "/settings", Settings]]],
] as const;

export function ThemeProvider({ children }: { children: ReactNode }) {
  const [dark, setDark] = useState(false);
  useEffect(() => { const saved = localStorage.getItem("polarops-theme"); const value = saved ? saved === "dark" : matchMedia("(prefers-color-scheme: dark)").matches; setDark(value); document.documentElement.classList.toggle("dark", value); }, []);
  const toggle = () => { const next = !dark; setDark(next); document.documentElement.classList.toggle("dark", next); localStorage.setItem("polarops-theme", next ? "dark" : "light"); };
  return <ThemeContext.Provider value={{ dark, toggle }}>{children}</ThemeContext.Provider>;
}
import { createContext, useContext } from "react";
const ThemeContext = createContext({ dark: false, toggle: () => {} });

function Sidebar({ mobile = false, close }: { mobile?: boolean; close?: () => void }) {
  const path = useRouterState({ select: s => s.location.pathname });
  return <aside className={`${mobile ? "w-full" : "hidden lg:flex w-60 fixed inset-y-0 left-0"} flex-col border-r bg-sidebar text-sidebar-foreground z-40`}>
    <div className="h-20 px-5 flex items-center border-b border-sidebar-border"><div className="h-9 w-9 bg-primary text-primary-foreground grid place-items-center mr-3"><Grid3X3 size={19}/></div><div><div className="font-display font-bold tracking-[0.14em]">POLAROPS</div><div className="text-[10px] text-muted-foreground uppercase">Antarctic Digital Twin</div></div></div>
    <nav className="flex-1 px-3 py-5 overflow-y-auto">{navGroups.map(([group, items]) => <div key={group} className="mb-5"><p className="px-3 mb-2 text-[10px] font-bold tracking-[0.18em] text-muted-foreground">{group}</p>{items.map(([label, to, Icon]) => <Link key={to} to={to} onClick={close} className={`relative flex items-center gap-3 px-3 h-10 mb-1 text-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${path === to ? "bg-sidebar-accent text-sidebar-accent-foreground font-semibold before:absolute before:left-0 before:h-5 before:w-0.5 before:bg-primary" : "text-muted-foreground hover:bg-sidebar-accent/60 hover:text-foreground"}`}><Icon size={17}/>{label}</Link>)}</div>)}</nav>
    <div className="border-t border-sidebar-border p-4 text-[10px] text-muted-foreground"><span className="status-dot bg-success mr-2"/>AODT CORE ONLINE<br/><span className="pl-4">SIH 2026 · PROTOTYPE</span></div>
  </aside>;
}

export function AppShell({ children }: { children: ReactNode }) {
  const { dark, toggle } = useContext(ThemeContext); const [menu, setMenu] = useState(false);
  return <div className="min-h-screen bg-background text-foreground"><Sidebar/><div className="lg:pl-60"><header className="sticky top-0 z-30 h-16 bg-background/95 backdrop-blur border-b flex items-center px-4 lg:px-7 gap-4"><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMenu(true)} aria-label="Open navigation"><Menu/></Button><div className="hidden md:flex items-center gap-7 flex-1">{[["STATION","BHARATI"],["STATE","WINTER"],["CONNECTIVITY","CONNECTED"],["SYNC","SYNCHRONIZED"]].map(([a,b])=><div key={a}><div className="command-label">{a}</div><div className="text-xs font-bold flex items-center gap-1.5">{a === "CONNECTIVITY" && <span className="status-dot bg-success"/>}{b}</div></div>)}</div><span className="demo-tag ml-auto md:ml-0">DEMO DATA</span><div className="hidden sm:block"><div className="command-label">TIME</div><div className="font-mono text-xs font-semibold">14:32:08 UTC</div></div><Button variant="ghost" size="icon" onClick={toggle} aria-label="Toggle theme">{dark ? <Sun/> : <Moon/>}</Button><Button variant="outline" size="icon" aria-label="System user"><UserRound/></Button></header><main className="p-4 sm:p-6 xl:p-8 max-w-[1680px] mx-auto">{children}</main></div>
  {menu && <div className="fixed inset-0 z-50 bg-foreground/40 lg:hidden"><div className="w-72 h-full"><Sidebar mobile close={() => setMenu(false)}/></div><Button size="icon" variant="secondary" className="absolute left-[18.5rem] top-4" onClick={()=>setMenu(false)}><X/></Button></div>}</div>;
}

export function StatusBadge({ value }: { value: string }) { const k = value.toLowerCase(); return <span className={`status-badge status-${k}`}>{value}</span>; }
export function PageHeader({ eyebrow, title, subtitle, status }: { eyebrow?: string; title: string; subtitle: string; status?: string }) { return <div className="mb-7 flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h1 className="page-title">{title}</h1><p className="text-muted-foreground mt-2 max-w-2xl text-sm leading-6">{subtitle}</p></div>{status && <StatusBadge value={status}/>}</div>; }
export function Panel({ title, subtitle, children, className="", action }: { title: string; subtitle?: string; children: ReactNode; className?: string; action?: ReactNode }) { return <section className={`panel ${className}`}><div className="panel-head"><div><h2 className="panel-title">{title}</h2>{subtitle && <p className="text-xs text-muted-foreground mt-1">{subtitle}</p>}</div>{action}</div><div className="p-5">{children}</div></section>; }

export function Topology({ large=false, selected, onSelect }: { large?: boolean; selected?: string; onSelect?: (id:string)=>void }) {
 const active = selected || "power";
 return <div className={`topology ${large ? "h-[590px]" : "h-[430px]"}`}>
   <svg className="absolute inset-0 w-full h-full" aria-hidden="true"><defs><pattern id="grid" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M 28 0 L 0 0 0 28" className="grid-line" fill="none"/></pattern></defs><rect width="100%" height="100%" fill="url(#grid)"/>{[[20,49,45,49],[45,49,73,30],[45,49,77,71],[20,49,18,80],[45,49,47,82],[45,49,43,17]].map((l,i)=><line key={i} x1={`${l[0]}%`} y1={`${l[1]}%`} x2={`${l[2]}%`} y2={`${l[3]}%`} className={active==="power" ? "dep-line active" : "dep-line"}/>)}</svg>
   {topologyNodes.map(n=><button key={n.id} onClick={()=>onSelect?.(n.id)} style={{left:`${n.x}%`,top:`${n.y}%`}} className={`twin-node ${active===n.id?"selected":""}`}><span className={`status-dot ${n.status==="CRITICAL"?"bg-critical":n.status==="WARNING"?"bg-warning":"bg-success"}`}/><span><strong>{n.name}</strong><small>{n.detail}</small></span></button>)}
   <div className="absolute bottom-4 left-4 flex flex-wrap gap-3 text-[10px] font-bold tracking-wider"><span><i className="status-dot bg-success"/> NOMINAL</span><span><i className="status-dot bg-warning"/> WARNING</span><span><i className="status-dot bg-critical"/> CRITICAL</span><span className="text-muted-foreground">━ DEPENDENCY</span></div>
 </div>;
}

function ExplanationDrawer({ open, setOpen }: { open:boolean; setOpen:(v:boolean)=>void }) { const sections = [["WHAT HAPPENED?","OBSERVED","Bearing vibration on G-02 exceeded the configured warning threshold by 0.6 percentage points."],["WHY DOES IT MATTER?","DERIVED","G-02 currently contributes 42% of active generation. Degradation reduces station power redundancy."],["WHAT DEPENDS ON IT?","DERIVED","Power Bus A supplies the habitat and science laboratory. Fuel operations also depend on the power system."],["WHAT COULD HAPPEN NEXT?","ILLUSTRATIVE","Continued load escalation may increase vibration and require transfer to backup generation."],["WHAT SHOULD THE OPERATOR REVIEW?","ILLUSTRATIVE","Inspect bearing condition, confirm G-01 availability, and verify reserve capacity before load changes."]]; return <Sheet open={open} onOpenChange={setOpen}><SheetContent className="sm:max-w-xl overflow-y-auto"><SheetHeader className="border-b pb-5"><div className="eyebrow">INCIDENT EXPLANATION</div><SheetTitle>G-02 · INCIDENT EXPLANATION</SheetTitle><SheetDescription>Decision-support context for operator review.</SheetDescription></SheetHeader><div className="py-4">{sections.map(([h,l,t],i)=><div className="explain-step" key={h}><span className="font-mono text-xs text-primary">0{i+1}</span><div><h3 className="text-xs font-bold tracking-wider">{h}</h3><span className="demo-tag my-2 inline-block">{l}</span><p className="text-sm text-muted-foreground leading-6">{t}</p></div></div>)}</div><div className="notice">This explanation is illustrative demo reasoning and requires human validation.</div></SheetContent></Sheet>; }

export function OverviewPage() { const [explain,setExplain]=useState(false); const [reason,setReason]=useState(true);
 return <><PageHeader eyebrow="STATION BHARATI · WINTER OPERATIONS" title="Operational Command Center" subtitle="Common operational picture for station infrastructure, environment, personnel and logistics." status="OPERATIONAL"/>
 <div className="section-label">OPERATIONAL METRICS</div><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4 mb-6">{demoMetrics.map((m,i)=><div className="metric-card" key={m.label}><div className="flex justify-between"><span className="eyebrow">{m.label}</span>{i===0?<Zap className="text-primary" size={18}/>:i===1?<Fuel className="text-warning" size={18}/>:i===2?<Users size={18}/>:<Activity size={18}/>}</div><div className="metric-value">{m.value}</div><p className="text-xs text-muted-foreground">{m.detail}</p><div className="mt-5 flex justify-between"><StatusBadge value={m.status}/><span className="demo-label">MEASURED · DEMO</span></div></div>)}</div>
 <div className="grid xl:grid-cols-[1.55fr_1fr] gap-6 mb-6"><Panel title="STATION DIGITAL TWIN" subtitle="Operational topology and dependency state" action={<span className="demo-tag">DEMO OPERATIONAL MODEL</span>}><Topology onSelect={(id)=>{if(id==="power") location.href="/digital-twin?asset=power"}}/></Panel><div className="space-y-6"><Panel title="CRITICAL OPERATIONAL EVENT" action={<StatusBadge value="CRITICAL"/>}><div className="text-lg font-bold mb-4">{demoG02.name}</div><div className="data-list">{demoG02.telemetry.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><div className="demo-label my-4">ILLUSTRATIVE DEMO TELEMETRY</div><div className="flex flex-wrap gap-2"><Button onClick={()=>location.href="/digital-twin?asset=power"}>INSPECT G-02</Button><Button variant="outline" onClick={()=>location.href="/digital-twin?asset=power"}>VIEW DEPENDENCIES</Button><Button variant="outline" onClick={()=>setExplain(true)}>OPEN EXPLANATION</Button></div></Panel><Panel title="G-02 · ASSET INTELLIGENCE"><div className="eyebrow mb-3">CURRENT CONDITION</div><div className="vibration"><span>VIBRATION</span><div className="vibration-bars">{[4,7,10,15,23,35,24,16,10,6,4].map((h,i)=><i key={i} style={{height:h}}/>)}</div><strong>+3.1%</strong></div><div className="data-grid">{demoG02.condition.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><div className="demo-label mt-4">ILLUSTRATIVE DEMO TELEMETRY</div></Panel></div></div>
 <div className="grid xl:grid-cols-2 gap-6 mb-6"><Panel title="INCIDENT TIMELINE"> <div className="timeline">{demoTimeline.map(([t,e])=><div key={t}><time>{t}</time><i/><span>{e}</span></div>)}</div></Panel><Panel title="CAUSAL REASONING" action={<Button variant="ghost" size="icon" onClick={()=>setReason(!reason)}>{reason?<ChevronDown/>:<ChevronRight/>}</Button>}>{reason&&<div className="reasoning">{[["EVENT","G-02 vibration deviation"],["CONTEXT","Generator operating conditions"],["IMPACT","Reduced power redundancy"],["FUTURE","Potential escalation"],["DECISION","Inspect G-02 and verify redundancy"],["OUTCOME","Awaiting operator approval"]].map(([a,b],i)=><div key={a}><span>{String(i+1).padStart(2,"0")}</span><div><b>{a}</b><p>{b}</p></div></div>)}</div>}<div className="demo-label mt-4">ILLUSTRATIVE DECISION TRACE</div></Panel></div>
 <div className="grid xl:grid-cols-[1fr_1.2fr] gap-6 mb-6"><Panel title="OPERATIONAL DEPENDENCY MODEL"><div className="space-y-3">{demoDependencies.map((row,i)=><div className="dependency-row" key={i}>{row.map((x,j)=><span key={x}><b>{x}</b><small>{j===0?"ASSET":j===1?"SUBSYSTEM":"OPERATION"}</small>{j<2&&<ChevronRight/>}</span>)}</div>)}</div></Panel><Panel title="OPERATIONAL RECOMMENDATION"><div className="recommendation"><div><span>RECOMMENDED ACTION</span><p>Inspect G-02 operating condition and verify backup generation capacity before further load escalation.</p></div><div><span>RATIONALE</span><p>Observed deviation may affect available power redundancy under current operating conditions.</p></div><div className="grid grid-cols-2"><p><span>CONFIDENCE</span><b>DEMO · 87%</b></p><p><span>PROVENANCE</span><b>ILLUSTRATIVE REASONING</b></p></div></div><div className="flex gap-2 mt-5"><Button onClick={()=>setExplain(true)}>REVIEW DECISION</Button><Button variant="outline" onClick={()=>location.href="/scenarios"}>VIEW SCENARIO</Button></div></Panel></div>
 <Panel title="HUMAN-IN-THE-LOOP CONTROL" className="mb-6"><div className="human-flow">{["DETECTION","ANALYSIS","RECOMMENDATION","HUMAN REVIEW","APPROVAL","ACTION"].map((x,i)=><span key={x} className={x==="HUMAN REVIEW"?"active":""}>{x}{i<5&&<ChevronRight/>}</span>)}</div><p className="text-center text-sm mt-5 text-muted-foreground">PolarOps provides decision support. <b className="text-foreground">Operational actions require human approval.</b></p></Panel>
 <Panel title="OPERATIONAL ACTIVITY" action={<span className="demo-tag">DEMO ACTIVITY</span>}><div className="activity-list">{demoActivities.map(([t,e,s])=><div key={t}><time>{t}</time><span>{e}</span><StatusBadge value={s}/></div>)}</div></Panel><ExplanationDrawer open={explain} setOpen={setExplain}/></>;
}

export function DigitalTwinPage(){ const [selected,setSelected]=useState("power"); const [zoom,setZoom]=useState(1); const node=topologyNodes.find(n=>n.id===selected) ?? topologyNodes[0]; return <><PageHeader eyebrow="AODT · LIVE OPERATIONAL MODEL" title="Station Digital Twin" subtitle="Interactive infrastructure topology, dependency paths and operational impact." status="SYNCHRONIZED"/><div className="grid xl:grid-cols-[1fr_330px] gap-6"><Panel title="BHARATI · OPERATIONAL TOPOLOGY" subtitle="Select an asset to trace its active dependency path" action={<div className="flex gap-1"><Button variant="outline" size="icon" onClick={()=>setZoom(Math.min(1.3,zoom+.1))} aria-label="Zoom in"><Plus/></Button><Button variant="outline" size="icon" onClick={()=>setZoom(Math.max(.8,zoom-.1))} aria-label="Zoom out"><Minus/></Button><Button variant="outline" size="icon" onClick={()=>setZoom(1)} aria-label="Reset view"><RotateCcw/></Button></div>}><div style={{transform:`scale(${zoom})`}} className="transition-transform origin-center"><Topology large selected={selected} onSelect={setSelected}/></div></Panel><Panel title="ASSET INFORMATION" action={<StatusBadge value={node.status}/>}><div className="text-xl font-bold mb-5">{node.name}</div><div className="data-list">{[["Asset",node.name],["System",selected==="power"?"Power Generation":"Station Infrastructure"],["Status",node.status],["Dependencies",selected==="power"?"Power Bus A · Habitat · Lab":"Power · Data"],["Impact",selected==="power"?"Reduced generation redundancy":"Local degradation"],["Last update","14:32:04 UTC"]].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><div className="notice mt-5">Selected dependency path is highlighted in the operational model.</div></Panel></div></> }

export function StationsPage(){ return <><PageHeader eyebrow="ANTARCTIC OPERATIONS" title="Station Portfolio" subtitle="Operational readiness across Indian Antarctic research stations."/><div className="grid md:grid-cols-2 gap-5">{demoStationData.stations.map((s,i)=><div className="station-card" key={s.name} onClick={()=>i===0&&(location.href="/")} tabIndex={0}><div className="station-index">0{i+1}</div><div><span className="eyebrow">INDIAN ANTARCTIC STATION</span><h2>{s.name}</h2><StatusBadge value={s.state}/></div><div className="station-stats">{[["CONNECTIVITY",s.connectivity],["PERSONNEL",s.personnel],["POWER STATE",s.power],["ALERT COUNT",s.alerts]].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><Button variant="outline">OPEN STATION <ChevronRight/></Button></div>)}</div></> }
export function ResourcesPage(){ return <><PageHeader eyebrow="SUPPLY & SUSTAINMENT" title="Resource & Logistics" subtitle="Current station resources, consumption and operational reserves."/><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{demoResources.map(([n,v,s,c,r])=><div className="resource-card" key={n as string}><div className="flex justify-between"><h2>{n}</h2><StatusBadge value={s as string}/></div><div className="resource-number">{v}%</div><div className="resource-track"><i style={{width:`${v}%`}}/></div><div className="grid grid-cols-2 gap-3 mt-5 text-xs"><div><span>CONSUMPTION</span><strong>{c}</strong></div><div><span>RESERVE</span><strong>{r}</strong></div></div><div className="demo-label mt-5">UPDATED 14:30 UTC · DEMO</div></div>)}</div></> }
export function ScenariosPage(){ const [run,setRun]=useState<string|null>(null); return <><PageHeader eyebrow="DECISION SUPPORT" title="Scenario Simulation" subtitle="Explore operational consequences before action. All outcomes are illustrative."/><div className="grid lg:grid-cols-[.9fr_1.1fr] gap-6"><div className="space-y-3">{demoScenarios.map(([n,d,a,r])=><button className={`scenario-item ${run===n?"selected":""}`} key={n} onClick={()=>setRun(n)}><div><h2>{n}</h2><p>{d}</p><span>AFFECTED · {a}</span></div><StatusBadge value={r}/><Button onClick={(e)=>{e.stopPropagation();setRun(n)}}>RUN SCENARIO</Button></button>)}</div><Panel title={run ? `${run} · RESULT` : "SIMULATION OUTPUT"} action={run&&<span className="demo-tag">SIMULATED RESULT · DEMO</span>}>{run?<div className="simulation-result"><BarChart3/><h3>Operational impact</h3><p>Station can maintain essential operations with reduced redundancy for approximately 18 hours.</p><h3>Affected dependencies</h3><p>Power Bus A → Habitat heating → Science cold storage</p><h3>Resource impact</h3><p>Backup fuel consumption increases by an estimated 24%.</p><h3>Recommended mitigation</h3><p>Transfer non-essential loads, verify backup generation, and prepare an operator-approved maintenance window.</p><Button>REVIEW MITIGATION</Button></div>:<div className="empty-state"><Activity/><p>Select a scenario and run the simulation to view its operational impact.</p></div>}</Panel></div></> }
export function ResiliencePage(){ const rows=[["POWER REDUNDANCY","ATTENTION","G-02 anomaly reduces N+1 margin"],["FUEL AUTONOMY","WATCH","81 days at current consumption"],["COMMUNICATIONS","NOMINAL","Primary and secondary links available"],["LIFE SUPPORT","NOMINAL","Environmental systems within limits"],["LOGISTICS","WATCH","Weather window constrained"],["DATA SYNCHRONIZATION","NOMINAL","All priority datasets synchronized"]]; return <><PageHeader eyebrow="OPERATIONAL ASSURANCE" title="Station Resilience" subtitle="Capability-level readiness without reductive composite scoring."/><Panel title="RESILIENCE DOMAINS" subtitle="Evidence-based operational status"><div className="resilience-list">{rows.map(([a,b,c],i)=><div key={a}><span className="index">0{i+1}</span><div><h3>{a}</h3><p>{c}</p></div><StatusBadge value={b}/><div className="resilience-bars">{[1,2,3,4,5].map(x=><i className={x<(b==="NOMINAL"?5:b==="WATCH"?4:3)?"on":""} key={x}/>)}</div></div>)}</div></Panel></> }
export function AlertsPage(){ const [filter,setFilter]=useState("ALL"); const [reviewed,setReviewed]=useState<number[]>([]); return <><PageHeader eyebrow="EVENT MANAGEMENT" title="Operational Alerts" subtitle="Prioritized conditions requiring awareness or operator review."/><div className="flex gap-2 mb-5">{["ALL","CRITICAL","WARNING","INFO"].map(f=><Button key={f} variant={filter===f?"default":"outline"} onClick={()=>setFilter(f)}>{f}</Button>)}</div><div className="space-y-3">{demoAlerts.filter(a=>filter==="ALL"||a.level===filter).map(a=><div className={`alert-row ${reviewed.includes(a.id)?"reviewed":""}`} key={a.id}><AlertTriangle/><div><StatusBadge value={a.level}/><h2>{a.text}</h2><span>{a.time} · DEMO DATA</span></div><Button variant="outline" disabled={reviewed.includes(a.id)} onClick={()=>setReviewed([...reviewed,a.id])}><ClipboardCheck/>{reviewed.includes(a.id)?"REVIEWED":"MARK AS REVIEWED"}</Button></div>)}</div></> }
export function ReportsPage(){ const [msg,setMsg]=useState(""); return <><PageHeader eyebrow="MISSION RECORD" title="Operational Reports" subtitle="Review and export station status, incident and simulation records."/>{msg&&<div className="notice mb-4">{msg}</div>}<div className="grid md:grid-cols-2 gap-4">{demoReports.map((r,i)=><div className="report-card" key={r}><div className="report-icon"><FileText/></div><div><span>REPORT · 0{i+1}</span><h2>{r}</h2><p>Generated from synchronized demo operational data.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setMsg(`${r} opened in demo preview.`)}>VIEW</Button><Button onClick={()=>setMsg(`${r} export prepared for demonstration.`)}><Download/> EXPORT</Button></div></div>)}</div></> }
export function SettingsPage(){ const {dark,toggle}=useContext(ThemeContext); const [critical,setCritical]=useState(true),[warnings,setWarnings]=useState(true),[system,setSystem]=useState(false); return <><PageHeader eyebrow="POLAROPS CONFIGURATION" title="System Settings" subtitle="Configure this local operational demonstration environment."/><div className="grid xl:grid-cols-2 gap-6"><Panel title="APPEARANCE"><SettingRow title="Dark operations theme" detail="Use Antarctic night operations colors"><Switch checked={dark} onCheckedChange={toggle}/></SettingRow></Panel><Panel title="OPERATIONS"><SelectRow title="Station" options={["BHARATI","MAITRI"]}/><SelectRow title="Default view" options={["Command Center","Digital Twin","Alerts"]}/><SelectRow title="Refresh interval" options={["30 seconds","1 minute","5 minutes"]}/></Panel><Panel title="NOTIFICATIONS"><SettingRow title="Critical alerts" detail="Conditions requiring immediate review"><Switch checked={critical} onCheckedChange={setCritical}/></SettingRow><SettingRow title="Warnings" detail="Emerging operational conditions"><Switch checked={warnings} onCheckedChange={setWarnings}/></SettingRow><SettingRow title="System notifications" detail="Synchronization and maintenance events"><Switch checked={system} onCheckedChange={setSystem}/></SettingRow></Panel><Panel title="SYSTEM"><SettingRow title="Demo mode" detail="Centralized local demonstration data"><StatusBadge value="ACTIVE"/></SettingRow><SettingRow title="Data provenance" detail="Measured, derived and illustrative labels"><Button variant="outline">VIEW</Button></SettingRow><SettingRow title="About PolarOps" detail="AODT · Smart India Hackathon 2026"><span className="font-mono text-xs">v0.1.0</span></SettingRow></Panel></div></> }
function SettingRow({title,detail,children}:{title:string;detail:string;children:ReactNode}){return <div className="setting-row"><div><h3>{title}</h3><p>{detail}</p></div>{children}</div>}; function SelectRow({title,options}:{title:string;options:string[]}){return <div className="setting-row"><label>{title}</label><select aria-label={title}>{options.map(o=><option key={o}>{o}</option>)}</select></div>}